apiVersion: v1
kind: Service
metadata:
  name: klee-sunwell
  namespace: prod
spec:
  type: NodePort
  selector:
    app: klee
  ports:
    - name: http
      port: 7071
      protocol: TCP
      targetPort: 7071
      nodePort: 30011
